apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ****-data-pvc
  namespace: database
spec:
  selector:
    matchLabels:
      app: db
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi